"""Fix errors

Revision ID: 6f9ead17747e
Revises: a60d2aedf652
Create Date: 2017-12-06 01:54:29.396788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9ead17747e'
down_revision = 'a60d2aedf652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('term', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'term')
    # ### end Alembic commands ###
