"""Add image model

Revision ID: 898425ec69ea
Revises: 6e845b068854
Create Date: 2017-12-02 19:29:29.309394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898425ec69ea'
down_revision = '6e845b068854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('alternate', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'alternate')
    # ### end Alembic commands ###
